apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-web-app
  template:
    metadata:
      labels:
        app: static-web-app
    spec:
      containers:
      - name: static-web-app
        image: gcr.io/project-id/static-web-app:v1
        ports:
        - containerPort: 80
